name: music-genre-demo-streamlit
dependencies:
    - python=3.11.4
    - pip==23.2
    - streamlit==1.24.1
    - matplotlib==3.7.2
    - numpy==1.25.1
    - plotly==5.9.0
    - scikit-learn==1.2.2
    - seaborn==0.12.2
    - joblib==1.2.0
    - pip:
        - torch==2.0.1
        - torchaudio==2.0.2
        - ffmpeg-python=0.2.0
        - pytube==15.0.0